# Generated by Django 2.0.7 on 2019-06-15 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=120, verbose_name='Описание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('criticality', models.CharField(choices=[('W', 'Срочно'), ('M', 'Несрочно'), ('L', 'Бессрочно')], max_length=1, verbose_name='Критичность')),
            ],
        ),
    ]
