# Generated by Django 2.0.7 on 2019-06-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='criticality',
            field=models.CharField(choices=[('W', 'Срочно'), ('M', 'Несрочно'), ('L', 'Бессрочно')], max_length=2, verbose_name='Критичность'),
        ),
    ]
